### ISSUE TITLE
Example alternating_routes.py not running

### ISSUE THREAD

**Issue by tproffen** [intelino-code/intelino-trainlib-async-py#5]
I am running in Windows 11 using Anaconds and Python 3.9.13. When running python alternate_routes.py, I get this error

`(base) C:\Users\thoma\GitHub\SmartTrain\Python\examples-async>python alternating_routes.py
Traceback (most recent call last):
  File "C:\Users\thoma\GitHub\SmartTrain\Python\examples-async\alternating_routes.py", line 4, in <module>
    from intelino.trainlib_async import (
ImportError: cannot import name 'TrainMsg' from 'intelino.trainlib_async' (C:\Users\thoma\anaconda3\lib\site-packages\intelino\trainlib_async\__init__.py)`

Pokes around a bit, but cannot figure out the issue.

**Comment by petrusek** [comment]
It seems `TrainMsg` is not exported on the top level...
Could you please try updating the import of `TrainMsg` (and the one after it) to load from `trainlib_async.messages`:
```python
from intelino.trainlib_async.messages import (
    TrainMsg,
    TrainMsgEventSnapCommandDetected,
)
```

**Comment by tproffen** [comment]
That works. I am working through the examples and will probably send a pull request with the updated code later today :)
